# Window/Game
DEF_BKGDCOLOR = (1, 1, 1, 1)  # white
GRID_TILE_LENGTH = 40
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

# Default tile
DEFAULT_GROUP = 0
DEFAULT_COLLISION_TYPE = 0

# Opening tile
OPENING_GROUP = 2
OPENING_COLLISION_TYPE = 2

# Encasing tile
ENCASING_GROUP = 3
ENCASING_COLLISION_TYPE = 3

# Ant
ANT_GROUP = 1
ANT_COLLISION_TYPE = 1
ANT_LENGTH = 20
