# Window/Game
DEF_BKGDCOLOR = (1, 1, 1, 1)  # white
GRID_TILE_LENGTH = 5
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

# KEYS
UP = 'up'
DOWN = 'down'
LEFT = 'left'
RIGHT = 'right'

# Default tile
DEFAULT_GROUP = 0
DEFAULT_COLLISION_TYPE = 0
TILE_ID = 'TILE'

# DIRT tile
DIRT_GROUP = 2
DIRT_COLLISION_TYPE = 2
DIRT_HP = 100
DIRT_ID = 'DIRT'

# Encasing tile
ENCASING_GROUP = 3
ENCASING_COLLISION_TYPE = 3
ENCASING_ID = 'ENCASING'

# Ant
ANT_GROUP = 1
ANT_COLLISION_TYPE = 1
ANT_LENGTH = 20
ANT_DIG_SPEED = 1
ANT_ID = 'ANT'
